config/routes.rb
FiestaWeb::Application.routes.draw do
  get "location/index"

  match 'lokasi' => 'location#index', :via => :get

  get "blog/index"

  get "blog/show"

  get "registrations/create"

  resources :rating

  devise_for :users

  get "produk/index"
  
  resources :customers
  get "customers/new"

  resources :berita

  resources :recipes

  resources :konsultasi
  get "konsultasi/index"

  resources :faq
  get "faq/index"

  resources :about
  get "about/index"

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :gallery
  get "gallery/index"

  namespace :manage do
    resources :dashboard, :products, :konsultasis, :galleries, :recipes
  end

  get "home/index"
  root :to => 'home#index'

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ratings
  
  attr_accessible :description, :full_name, :ingredient, :step, :title, :image, :approved
  
  validates :description, :presence => true
  validates :full_name, :presence => true
  validates :ingredient, :presence => true
  validates :step, :presence => true
  validates :title, :presence => true
  validates :image, :attachment_presence => true
  
  has_attached_file :image, :styles => { :small => "200*150>", :medium => "499x280>", :thumb => "100x100>" }, 
                            :default_url => "/images/:style/missing.png",
                            :url => "/system/:class/:attachment/:id_partition/:style/:basename.:extension",
                            :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:basename.:extension"
  
  before_create :randomize_file_name
  
  private

  def randomize_file_name
    extension = File.extname(image_file_name).downcase
    self.image.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :check_for_mobile, :only => [:index, :show]
    
  layout "front"
  
  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.where(:approved => 1)
    @bodyid = "fiesta_resep"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_rating = Rating.find_by_recipe_id(params[:id])
    @popular_recipe = Recipe.joins(:ratings)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new
    @bodyid = "fiesta_kontak"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for @recipe, :url => recipes_path, :html => { :multipart => true } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
	<tr>
		<td class="fiesta_resep"><strong>Your Name</strong></td>
		<td><%= f.text_field :full_name, :class =>"fiesta_input_text", :style => "margin-bottom: 5px;" %></td>
	</tr>
	<tr>
		<td class="fiesta_resep"><strong>Title</strong></td>
		<td><%= f.text_field :title, :class =>"fiesta_input_text" %></td>
	</tr>
	<tr>
		<td class="fiesta_resep"><strong>Upload Photo</strong></td>
		<td style="vertical-align:middle; height: 80px;">
			<%= f.file_field :image %>
			<p><em>(JPG or PNG ; no more than 1 MB)</em></p>
		</td>
	</tr>
	<tr>
		<td class="fiesta_resep"><strong>Description</strong></td>
		<td><%= f.text_area :description, :class => "fiesta_input_text" %></td>
	</tr>
	<tr>
		<td class="fiesta_resep"><strong>Ingredients</strong></td>
		<td><%= f.text_area :ingredient, :class => "fiesta_input_text" %></td>
	</tr>
	<tr>
		<td class="fiesta_resep"><strong>Steps</strong></td>
		<td><%= f.text_area :step, :class => "fiesta_input_text" %></td>
	</tr>
	<tr>
		<td></td>
		<td style="padding-top: 20px;"><%= f.submit "SUBMIT", :class => "fiesta_resep_btn" %></td>
	</tr>
</table>
<% end %>

app/views/recipes/edit.html.erb
<%=
content_for :title do
	"Edit Recipe | Fiesta Seafood"
end
%>
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%=
content_for :title do
	"Resep | Fiesta Seafood"
end
%>
<div id="fiesta_right_side">
	<h1>RESEP</h1>
	<div id="fiesta_galeri_content">
		<h2>Kirim resep terbaik kamu kesini!</h2>
		<p>Fiesta Seafood memang merupakan makanan praktis tapi ternyata tidak sedikit juga orang yang memasaknya menggunakan resep favorit sesuai selera masing-masing. Oleh karena itu ayo kirimkan resep favorit kamu kesini agar banyak keluarga Fiesta Seafood yang ketagihan resep rahasia kamu.</p>
		<p class="fiesta_galeri_upload">
			<% if user_signed_in? %>
			<%= link_to 'SUBMIT RECIPE', new_recipe_path, :class => "fiesta_galeri_upload_btn" %>
			<% else %>
			<%= link_to 'SUBMIT RECIPE', '#', :class => "fiesta_galeri_upload_btn", :onclick => "openUpload()" %>
			<% end %>
		</p>
		<h3>ALL RECIPES</h3>
		<table id="fiesta_recipe_list_table">
			<tr>
		<% 
			@recipes.each do |row|
		%>	
				<td class="fiesta_recipe_list_pic">
					<div class="picture_recipe_list">
					<%= link_to((image_tag row.image.url(:small)), recipe_path(row)) %>
					</div>
					<div class="title_recipe_list">
					<%= link_to row.title, recipe_path(row) %>
					</div>
				</td>
		<%
			end 
		%>
			</tr>
			</tr>
		</table>
		<div class="clearfix"></div>
	</div>
</div>

<div class="clearfix"></div>

app/views/recipes/new.html.erb
<%=
content_for :title do
	"Kirim Resep | Fiesta Seafood"
end
%>
<div class="fiesta_container">
	<div id="fiesta_right_side">
		<h1>RESEP</h1>
		<div id="fiesta_resep_submit">
			<%= render 'form' %>
		</div>
		
		<div class="clearfix"></div>
		
	</div>
	
	<div class="clearfix"></div>
</div>

app/views/recipes/show.html.erb
<%=
content_for :title do
	"#{@recipe.title} | Fiesta Seafood"
end
%>
<div id="fiesta_right_side">
	<h1>RESEP</h1>
	<div id="fiesta_berita_detail">
		<%= image_tag @recipe.image.url(:medium) %>
		<table>
			<tr>
				<td style="width: 50px;"><p><strong>Penilaian</strong></p></td>
				<td>
					<ul class="fiesta_star_rating">
						<li>
							<% if @recipe_rating %>
                            <div data-productid="<%= @recipe.id %>" class="rateit" data-rateit-value="<%= @recipe_rating.rating/5 %>" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
                            <% else %>
                            <div data-productid="<%= @recipe.id %>" class="rateit" data-rateit-value="0" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
                            <% end %>
						</li>
					</ul>
				</td>
			</tr>
		</table>
		<h2><%= @recipe.title %></h2>
		<p><%= @recipe.description.html_safe %></p>
		<p><strong>Komposisi</strong></p>
		<p><%= @recipe.ingredient.html_safe %></p>
		<p><strong>Cara memasak</strong></p>
		<p><%= @recipe.step.html_safe %></p>
		<p><strong>Pendapat kamu tentang resep ini</strong></p>
		<div id="disqus_thread"></div>
		<script type="text/javascript">
	        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
	        var disqus_shortname = 'fiestaseafood'; // required: replace example with your forum shortname
	
	        /* * * DON'T EDIT BELOW THIS LINE * * */
	        (function() {
	            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
	            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
	            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	        })();
	    </script>
	    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
	    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
		<% if user_signed_in? %>
		<table style="margin: 0 auto 0 auto;">
			<tr>
				<td style="padding-top: 5px;"><p><strong>Ayo nilai resep ini &nbsp;&nbsp;&nbsp;</strong></p></td>
				<td>
					<ul class="fiesta_star_rating">
						<li><div data-productid="<%= @recipe.id %>" id="rate-me-now" class="rateit"></div></li>
					</ul>
				</td>
			</tr>
		</table>
		<% else %>
		<table style="margin: 0 auto 0 auto;">
			<tr>
				<td style="padding-top: 5px;"><p><strong>Login dulu sebelum menilai &nbsp;&nbsp;&nbsp;</strong></p></td>
				<td>
					<ul class="fiesta_star_rating">
						<li>
							<% if @recipe_rating %>
                            <div data-productid="<%= @recipe.id %>" class="rateit" data-rateit-value="<%= @recipe_rating.rating/5 %>" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
                            <% else %>
                            <div data-productid="<%= @recipe.id %>" class="rateit" data-rateit-value="0" data-rateit-ispreset="true" data-rateit-readonly="true"></div>
                            <% end %>
						</li>
					</ul>
				</td>
			</tr>
		</table>
		<% end %>
	</div>
	
	<div id="fiesta_berita_list">
		<h1>RESEP POPULER</h1>
		<% @popular_recipe.each do |popular| %>
		<div class="fiesta_resep_list_small">
			<%= image_tag popular.image.url(:medium), :width => "200" %>
			<a href="<%= recipe_path(popular.id) %>"><%= popular.title %></a>
		</div>
		<% end %>
	</div>
	
</div>

<%= javascript_include_tag "jquery.rateit.min", :debug => true %>

<script>
	$('#rate-me-now').rateit({max: 5, step: 1});
	
	$('#rate-me-now').bind('rated reset', function (e) {
		var ri = $(this);
		var value = ri.rateit('value');
		var productID = ri.data('productid');
		
		ri.rateit('readonly', true);
		
		// sent to backend
		$.ajax({
			url: '<%= rating_index_path %>',
			data: { id: productID, value: value },
			type: 'POST',
			success: function(data) {
				console.log(data);
			},
			error: function(jxhr, msg, err) {
				console.log(msg);
			}
		});
	});
</script>