config/routes.rb
FiestaWeb::Application.routes.draw do
  get "location/index"

  match 'lokasi' => 'location#index', :via => :get

  get "blog/index"

  get "blog/show"

  get "registrations/create"

  resources :rating

  devise_for :users

  get "produk/index"
  
  resources :customers
  get "customers/new"

  resources :berita

  resources :recipes

  resources :konsultasi
  get "konsultasi/index"

  resources :faq
  get "faq/index"

  resources :about
  get "about/index"

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post

  resources :gallery
  get "gallery/index"

  namespace :manage do
    resources :dashboard, :products, :konsultasis, :galleries, :recipes
  end

  get "home/index"
  root :to => 'home#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :like, :title, :user_id, :image, :approved
  
  validates :image, :attachment_presence => true
  validates :title, :presence => true
  
  has_attached_file :image, :styles => { :thumb => "70*70", :small => "250*100>", :medium => "680*480>"}, 
                            :default_url => "/images/:style/missing.png",
                            :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:basename.:extension"
  
  before_create :randomize_file_name
  
  private

  def randomize_file_name
    extension = File.extname(image_file_name).downcase
    self.image.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
  end

end

app/models/konsultasi.rb
class Konsultasi
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :name, :gender, :email, :phone, :address, :birthdate, :message
  
  validates :name, :gender, :email, :address, :birthdate, :message, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :name, :email, :body
  
  validates :name, :email, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :title, :main_image, :product_image, :ingredient_image, :cook_image
  
  validates :title, :presence => true
  
  has_attached_file :main_image, :styles => { :thumb => "70*70", :medium => "109*149>" },
                                 :default_url => "/images/:style/missing.png",
                                 :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:basename.:extension"
  
  has_attached_file :product_image, :styles => { :thumb => "70*70", :medium => "300*300>" },
                                    :default_url => "/images/:style/missing.png",
                                    :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:basename.:extension"
                                    
  has_attached_file :ingredient_image, :styles => { :thumb => "70*70", :medium => "300*300>" },
                                       :default_url => "/images/:style/missing.png",
                                       :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:basename.:extension"
                                       
  has_attached_file :cook_image, :styles => { :thumb => "70*70", :medium => "300*300>" },
                                 :default_url => "/images/:style/missing.png",
                                 :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:basename.:extension"
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :recipe
  
  attr_accessible :rating, :recipe_id
  
  validates :rating, :presence => true
  validates :recipe_id, :presence => true
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :ratings
  
  attr_accessible :description, :full_name, :ingredient, :step, :title, :image, :approved
  
  validates :description, :presence => true
  validates :full_name, :presence => true
  validates :ingredient, :presence => true
  validates :step, :presence => true
  validates :title, :presence => true
  validates :image, :attachment_presence => true
  
  has_attached_file :image, :styles => { :small => "200*150>", :medium => "499x280>", :thumb => "100x100>" }, 
                            :default_url => "/images/:style/missing.png",
                            :url => "/system/:class/:attachment/:id_partition/:style/:basename.:extension",
                            :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:basename.:extension"
  
  before_create :randomize_file_name
  
  private

  def randomize_file_name
    extension = File.extname(image_file_name).downcase
    self.image.instance_write(:file_name, "#{SecureRandom.hex(16)}#{extension}")
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  
  validates :name, :presence => true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_for_mobile, :only => [:index]
  
  layout "front"
  # Default method for the home page
  #
  # @param none
  def index
    @bodyid = "fiesta_home"
    
    # if accessed from mobile
    if :mobile_device?
      url = 'http://blog.fiestaseafood.com/api/index.php/category/9'
      response = Nestful.get(url)
      response_decode = response.decoded
      
      @wordpress = JSON.parse(response_decode)

    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/berita_helper.rb
module BeritaHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/produk_helper.rb
module ProdukHelper
end

app/helpers/rating_helper.rb
module RatingHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<%=
content_for :title do
	"Home | Fiesta Seafood"
end
%>

<div class="clearfix"></div>
    	
<div id="fiesta_main_balloon">
	<div id="shadow_fiesta_main_balloon"></div>
</div>
<div id="fiesta_main_slide">
	<div id="fiesta_arrow_left"><%= image_tag "fiesta_arrowleft_b.png" %></div>
	<div id="fiesta_main_slide_container">
		<ul id="fiesta_main_slide_boxes">
			<li>
				<div class="fiesta_slide_even">
					<div class="fiesta_slide_inner_left">
						<a href="http://meetchefarnold2.fiestaseafood.com" target="_blank">Segera Dapatkan Tiket Cooking Demo</a>
						<p><span>With Chef Arnold</span></p>
					</div>
					<div class="fiesta_slide_inner_right">
						<%= image_tag "meetchef2.jpg" %>
					</div>
					<div class="clearfix"></div>
				</div>
			</li>
			<li>
				<div class="fiesta_slide_even">
					<div class="fiesta_slide_inner_left">
						<a href="http://fiestaseafood.com/berita/135">Kampanye Ayo Makan <br />Seafood</a>
					</div>
					<div class="fiesta_slide_inner_right">
						<%= image_tag "image_press.png", :style => "position: relative; right: 35px; top: -25px;" %>
					</div>
					<div class="clearfix"></div>
				</div>
			</li>
			<li>
				<div class="fiesta_slide_even">
					<div class="fiesta_slide_inner_left">
						<a href="http://blog.fiestaseafood.com/2013/06/manfaat-seafood-untuk-kesehatan/">Manfaat Seafood</a>
						<p><span>Untuk Kesehatan</span></p>
					</div>
					<div class="fiesta_slide_inner_right"><%= image_tag "sep_seafood.png" %></div>
					<div class="clearfix"></div>
				</div>
			</li>
			<li>
				<div class="fiesta_slide_even">
					<div class="fiesta_slide_inner_left">
						<a href="<%= produk_index_path %>">Fiesta Seafood</a>
						<p><span>Produk olahan udang terbaik</span></p>
					</div>
					<div class="fiesta_slide_inner_right"><%= image_tag "fiesta_slide_produk.png", :style => "margin-left: 20px;" %></div>
					<div class="clearfix"></div>
				</div>
			</li>
			<li>
				<div class="fiesta_slide_even">
					<div class="fiesta_slide_inner_left">
						<a href="http://www.kisahseafoodramadhan.com/" target="_blank">Pengumuman Pemenang</a>
						<p><span>Kisah Seafood Ramadhan</span></p>
					</div>
					<div class="fiesta_slide_inner_right"><%= image_tag "sep_ramadhan.png", :style => "margin-left: 7px;" %></div>
					<div class="clearfix"></div>
				</div>
			</li>
			<li>
				<div class="fiesta_slide_even">
					<div class="fiesta_slide_inner_left">
						<a href="https://www.facebook.com/media/set/?set=a.131881290354490.1073741831.112121445663808&type=3" target="_blank">#MeetChefArnold</a>
						<p><span>Kejutan dari Fiesta Seafood</span></p>
					</div>
					<div class="fiesta_slide_inner_right"><%= image_tag "sep_arnold.png", :style => "margin-left: 7px;" %></div>
					<div class="clearfix"></div>
				</div>
			</li>
			<li>
				<div class="fiesta_slide_even">
					<div class="fiesta_slide_inner_left">
						<a href="<%= gallery_index_path %>">#Breakfiesta</a>
						<p><span>Kirim foto kamu makan Fiesta Seafood yuk</span></p>
					</div>
					<div class="fiesta_slide_inner_right"><%= image_tag "fiesta_slide_galeri.png" %></div>
					<div class="clearfix"></div>
				</div>
			</li>
			<li>
				<div class="fiesta_slide_even">
					<div class="fiesta_slide_inner_left">
						<a href="<%= recipes_path %>">Resep favorit</a>
						<p><span>Temukan resep Fiesta Seafood terbaik disini</span></p>
					</div>
					<div class="fiesta_slide_inner_right"><%= image_tag "fiesta_slide_resep.png" %></div>
					<div class="clearfix"></div>
				</div>
			</li>
			<li>
				<div class="fiesta_slide_even">
					<div class="fiesta_slide_inner_left">
						<a href="http://blog.fiestaseafood.com">Blog</a>
						<p><span>Kumpulan cerita Fiesta Seafood</span></p>
					</div>
					<div class="fiesta_slide_inner_right"><%= image_tag "fiesta_slide_blog.png" %></div>
					<div class="clearfix"></div>
				</div>
			</li>
		</ul>
	</div>
	<div id="fiesta_arrow_right"><%= image_tag "fiesta_arrowright_b.png" %></div>
	<div class="clearfix"></div>
</div>